metrics:
 global:
  scrape_interval: 60s
  configs:
   - name: hosted-prometheus
     scrape_configs:
      - job_name: node
        static_configs:
         - targets: ['localhost:9100', '127.0.0.1:9100']
           remote_write:
      - url: https://prometheus-us-central1.grafana.net/api/prom/push
        basic_auth:
        username: 793996
        password: eyJrIjoiYjQ4MTdiNmY2M2IzZmViYjM1YzgxYjdiMDk2NTFmMDU4Y2MzNWY4OSIsIm4iOiJncmFmYW5hLWFwaS1rZXkiLCJpZCI6ODAzNDEyfQ==EOF
